<?php

namespace App\Transformers;

use Illuminate\Database\Eloquent\Model;

/**
 * Class CourseTransformer.
 *
 * @package namespace App\Transformers;
 */
class CourseTransformer extends BaseTransformer
{
    public function transform(Model $model)
    {
        $attributes = parent::transform($model); // TODO: Change the autogenerated stub
        $attributes['cover_image'] = config('app.url') . '/images/' . $attributes['cover_image'];
        return $attributes;
    }
}
